[package]
name = "client"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
shared = { workspace = true }
bincode = { workspace = true }
js-sys = { workspace = true }
wasm-bindgen = { workspace = true }
wasm-bindgen-futures = { workspace = true }
web-sys = { workspace = true, features = [
    "CanvasRenderingContext2d",
    "HtmlCanvasElement",
    "console",
    "Document",
    "Element",
    "HtmlElement",
    "Node",
    "Window",
    "WebSocket",
    "MessageEvent",
    "CloseEvent",
    "ErrorEvent",
    "MouseEvent",
    "Location",
    "BinaryType",
    "Performance",
] }
anyhow = "1.0.100"
