[package]
name = "client"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
shared = { workspace = true }
bincode = { workspace = true }
js-sys = { workspace = true }
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
web-sys = { version = "0.3", features = [
    "CanvasRenderingContext2d",
    "HtmlCanvasElement",
    "console",
    "Document",
    "Element",
    "HtmlElement",
    "Node",
    "Window",
    "WebSocket",
    "MessageEvent",
    "CloseEvent",
    "ErrorEvent",
    "MouseEvent",
    "Location",
    "BinaryType",
    "Performance",
] }
anyhow = "1.0.100"
winit = { version = "0.30", features = ["serde"] }
console_error_panic_hook = "0.1.7"
