services:
  caddy:
    image: localhost/caddy
    pull_policy: never
    restart: unless-stopped
    container_name: caddy
    network_mode: host
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - /home/malcolm/caddy/data:/data
      - /home/malcolm/caddy/config:/config
